name: Gerar Animação da Snake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gerar:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Gerar animação a partir do arquivo de dados
        uses: Platane/snk/svg-only@v3
        with:
          outputs: |
            dist/github-contribution-grid-snake.svg?url=https://raw.githubusercontent.com/messias-code/messias-code/output/contribution-data.csv
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&url=https://raw.githubusercontent.com/messias-code/messias-code/output/contribution-data.csv

      - name: Enviar SVGs para o branch de saída
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
